yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.contrib.auth import views
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title_length = 200  # Default number. To be adjusted based on HTML design
    title = models.CharField(
        max_length=title_length,
        verbose_name='Название группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Строка адреса для группы'
    )
    description = models.TextField(
        verbose_name='Описание группы'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Перед вами чистый лист. Творите.'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа поста',
        help_text='В какую группу добавить пост'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Добавьте картинку'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Пост',
        help_text='Комментируемый пост'
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Что же вы об этом думаете?'
    )
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_user_author',
        )]

yatube/posts/forms.py
from django import forms
from django.forms import Textarea

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': Textarea(attrs={'cols': 40, 'rows': 10}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def get_page_context(request, posts):
    paginator = Paginator(posts, settings.ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.select_related('group', 'author').all()
    context = {
        'page_obj': get_page_context(request, posts),
    }
    template = 'posts/index.html'
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all().select_related('group', 'author')
    context = {
        'group': group,
        'title': group.title,
        'page_obj': get_page_context(request, posts),
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    user_profile = get_object_or_404(User, username=username)
    posts = user_profile.posts.all().select_related('group', 'author')
    count_posts = posts.count()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=user_profile,
    ).exists()
    context = {
        'user_profile': user_profile,
        'page_obj': get_page_context(request, posts),
        'count_posts': count_posts,
        'following': following
    }
    template = 'posts/profile.html'

    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user_profile = post.author
    form = CommentForm()
    comments = post.comments.all().select_related('post', 'author')
    context = {
        'post': post,
        'user_profile': user_profile,
        'form': form,
        'comments': comments,
    }
    template = 'posts/post_detail.html'
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)

    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user.username)


@login_required
def post_edit(request, post_id):
    changing_post = get_object_or_404(Post, id=post_id)

    if changing_post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=changing_post
    )

    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post_id = post_id
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.select_related('author').filter(
        author__following__user=request.user)
    context = {
        'page_obj': get_page_context(request, posts)
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    follower_user = request.user
    if author != follower_user:
        Follow.objects.get_or_create(user=follower_user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follower_user = request.user
    Follow.objects.filter(user=follower_user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/includes/add_comment.html
{% load user_filters %}

<div class="card my-4">
  <h5 class="card-header">Добавить комментарий:</h5>
  <div class="card-body">
    <form method="post" action="{% url 'posts:add_comment' post.id %}">
      {% csrf_token %}
      <div class="form-group mb-2">
        {{ form.text|addclass:"form-control" }}
        <small id="id_text-help" class="form-text text-muted">
          {{ form.text.help_text }}
        </small>
      </div>
      <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
  </div>
</div>

yatube/templates/posts/includes/post_list.html
{% load thumbnail %}

<article>
  <ul>
    {% if show_profile_link %}
      <li>
        Автор: 
        <a href="{% url 'posts:profile' post.author.username %}">
          {{ post.author.get_full_name }}
        </a>
      </li>
    {% endif %}
    <!-- Ссылка на группу будет под ссылкой на профиль автора,
      так получается аккуратнее и логичнее -->
    {% if show_group_link and post.group %}
      <li>
        Группа: 
        <a href="{% url 'posts:group_list' post.group.slug %}">
          {{ post.group.title }}
        </a>
      </li>
    {% endif %}
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x390" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>
    {{ post.text }}
  </p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
</article>

yatube/templates/posts/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
          class="nav-link {% if follow %}active{% endif %}"
          href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/posts/includes/view_comments.html
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <ul>
        <li>
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.get_full_name }}
            </a>
          </h5>
        </li>
        <li>
          Дата публикации: {{ comment.created|date:"d E Y" }} 
        </li>
      </ul>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}